export const GET_CANDIDATES_REQUEST = 'GET_CANDIDATES_REQUEST'
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS'
export const GET_CANDIDATES_FAIL = 'GET_CANDIDATES_FAIL'

export const CREATE_CANDIDATE_REQUEST = 'CREATE_CANDIDATE_REQUEST'
export const CREATE_CANDIDATE_SUCCESS = 'CREATE_CANDIDATE_SUCCESS'
export const CREATE_CANDIDATE_FAIL = 'CREATE_CANDIDATE_FAIL'

export const DELETE_CANDIDATE = 'DELETE_CANDIDATE'