export const GET_POSITIONS_REQUEST = 'GET_POSITIONS_REQUEST'
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS'
export const GET_POSITIONS_FAIL = 'GET_POSITIONS_FAIL'

export const CREATE_POSITION_REQUEST = 'CREATE_POSITION_REQUEST'
export const CREATE_POSITION_SUCCESS = 'CREATE_POSITION_SUCCESS'
export const CREATE_POSITION_FAIL = 'CREATE_POSITION_FAIL'

export const DELETE_POSITION = 'DELETE_POSITION'